server:
  port: '${PORT:8080}'
logging:
  level:
    org:
      atmosphere: warn
spring:
  mustache:
    check-template-location: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/requestsdb' # for change
    username: username # for change
    password: pass # for change
    hikari:
      connection-timeout: '30000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
vaadin:
  productionMode: true
  pnpm:
    enable: true
  frontend:
    hotdeploy: false
    bundle-build: true
  webpack:
    generatedFolder: target/classes/META-INF/resources