version: '3.9'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: username # for change
      POSTGRES_PASSWORD: pass # for change
      POSTGRES_DB: requestsdb # for change
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - "5000:5432"
    networks:
      - main

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/requestsdb # for change
      SPRING_DATASOURCE_USERNAME: username # for change
      SPRING_DATASOURCE_PASSWORD: pass # for change
      MAVEN_OPTS: "-Xmx2g"
    deploy:
      resources:
        limits:
          memory: 4g
    ports:
      - "8080:8080"
    networks:
      - main

#  nginx: # for change
#    image: nginx:latest
#    depends_on:
#      - app
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx/ssl:/etc/letsencrypt
#      - ./nginx/html:/usr/share/nginx/html
#      - ./nginx/logs:/var/log/nginx
#    networks:
#      - main
#    restart: always
#
#  certbot: # for change
#    image: certbot/certbot
#    volumes:
#      - ./nginx/ssl:/etc/letsencrypt
#      - ./nginx/html:/usr/share/nginx/html
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /usr/share/nginx/html --quiet; done;'"
#    depends_on:
#      - nginx
#    networks:
#      - main
#    restart: unless-stopped

volumes:
  postgres_data:

networks:
  main:
    external: true
